### ISSUE TITLE
🐛 [BUG] - [Process Sample_report] Pipeline fails on missing inputs

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#70]
### Description

If inputs are missing for the process `FOODME2:REPORTING:HELPER_SAMPLE_REPORT` then piepline fails with following error messsage:
```
WARN: Input tuple does not match tuple declaration in process `FOODME2:REPORTING:HELPER_SAMPLE_REPORT` -- offending value: [[sample_id:3554-03-k-MMX1a-2_S6_L001, single_end:false], null, /home/debian/NGS/Metabarcoding/work/5a/66de65a9e1830383d4265e070a9040/3554-03-k-MMX1a-2_S6_L001_R1_001.fastq.fastp.json]
WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
ERROR ~ Error executing process > 'FOODME2:REPORTING:HELPER_SAMPLE_REPORT (4)'

Caused by:
  Path value cannot be null
```

This is related to the discussion we had about checking what happens for bad samples.

Do you think it is possible to check if the output the the creating process are empty, and if it's the case add a dummy empty file to the channel instead of `null` (is there something like `touch`in nextflow)? 
The logic to check for empty files in the python script for the sample report would be straight forward to implement. The created JSON would miss some entries but this would already be picked up by the html report.

### Nextflow version

24.04.4

### Pipeline version

1.0.0

### Reproduction steps

```bash
nextflow run ...
```

### Deployment

Conda/Mamba

### OS

Linux

**Comment by gregdenay** [comment]
I have a "crappy dataset" to test this, let me know if you want it

**Comment by marchoeppner** [comment]
That dataset would be useful, right - any way to share that?

As for dealing with empty outputs - this here is a bit more complex since it is missing a bunch of outputs

```NEXTFLOW
tuple val(meta), path(composition), path(cutadapt), path(blast), path(consensus),path(fastp)
```

basically anything between meta and the fastp json is missing. 

Easiest to work on this with real data. In Nextflow, the way to have a "dummy" file would probably involve something like ch_dummy = file("${baseDir}/assets/dummy.txt"

It now depends on whether the upstream result is an empty file (probably not?) or whether it has no output period. When there is no output, the logic becomes a little bit more complex.

Should be doable anyway, but I need some data to test.

**Comment by marchoeppner** [comment]
Added a simple measure to prevent failed samples to break the reporting in fed7c6cf53981e973ba8fae3d42a453b5b3bc472

Next step could be to think about how a failed sample should appear in the report after all (e.g. dummy files). That will probably take a little while to get right.

**Comment by gregdenay** [comment]
I think we should produce a JSON sample report also for failed samples, with the data up to the step that failed (say fastp + cutadapt if clustering failed). The other field could me missing, it's easy enough to check for missing keys.

**Comment by gregdenay** [comment]
Marc -> Nextflow
Greg -> Python script

**Comment by marchoeppner** [comment]
a034a52 includes some initial changes to support the discussed update to the reporting (failed samples):

Right now, there is still a "safety" on by not forwarding any emissions that contain a null value at any of the channel positions (since we do not know which file(s) may be missing). Since the report script isn't yet able to deal with that, we are still preventing these channels to get into the report process. Once the script is changed, this little branching pattern can be removed.

```Nextflow
    ch_compo_json.join(
        ch_cutadapt, remainder: true
    ).join(
        ch_blast, remainder: true
    ).join(
        ch_consensus, remainder: true
    ).join(
        ch_fastp_json, remainder: true
    ).set { ch_reports_grouped }

    ch_reports_grouped.branch { it ->
        failed: it.contains(null)
        pass: !it.contains(null)
    }.set { ch_reports_grouped_with_status }
    
    ch_reports_grouped_with_status.failed.subscribe { it ->
        log.warn "${it[0].sample_id} classified as failed - will only created partial report."
    }

    /*
    Make a pretty JSON using the sample-specific reports and
    summary metrics from the clustering as well as software versions
    */
    HELPER_SAMPLE_REPORT(
        ch_reports_grouped_with_status.pass,
        ch_clustering.collect(),
        ch_versions.collect()
    )
```

**Comment by marchoeppner** [comment]
Fixed a rather severe issue in [2582edc](https://github.com/bio-raum/FooDMe2/commit/2582edc61e4de2e28ad0564b121105fbad1baa99) 

Bascially, a groovy/nextflow thing. The meta object was modified to store insert size and read length and report instances of read_length > insert_size. But that modification is global, not local, so the meta object of the main channel was also modified. Just a reminder to us that this always requires a new variable to store meta data in rather than modifying it in place...

Main consequence of this was that the meta object of the fastp json was potentially no longer compatible with the meta object of all the downstream process (one with and one without insert_size and mean_length).

**Comment by gregdenay** [comment]
[99527de](https://github.com/bio-raum/FooDMe2/commit/99527de55adf65ce78b5e0d45724d8149928ba28) implements the logic and python script modifications for this case. Contains all failed samples except the ones with too few reads. 
For this the logic in the cutadapt module needs to be changed, that's a Groovy job :) 

```groovy
CUTADAPT.out.reads.branch { m, r ->
        paired: !m.single_end
        single: m.single_end
    }.set { ch_reads_by_config }

    ch_failed_reads     = Channel.from([])
    ch_pass_reads       = Channel.from([])

    // all paired end samples
    ch_reads_by_config.paired.branch { m, r ->
        pass: file(r[0]).countFastq() >= params.min_reads
        fail: file(r[0]).countFastq() < params.min_reads
    }.set { ch_reads_pe_with_status }

    // all single-end samples
    ch_reads_by_config.single.branch { m, r ->
        pass: file(r).countFastq() >= params.min_reads
        fail: file(r).countFastq() < params.min_reads
    }.set { ch_reads_se_with_status }

    ch_failed_reads     = ch_failed_reads.mix(ch_reads_pe_with_status.fail, ch_reads_se_with_status.fail)
    ch_pass_reads       = ch_pass_reads.mix(ch_reads_pe_with_status.pass, ch_reads_se_with_status.pass)

    // Warn about failed samples based on a minimum number of required sequences
    ch_failed_reads.subscribe { m, r ->
        log.warn "Too few reads - stopping sample ${m.sample_id} after PCR primer removal!"
    }
```


One caveat, the sample_report module relies on `getSimpleName()` to get the sample id. 

```groovy
def prefix = task.ext.prefix ?: fastp.getSimpleName()
```

Fastp **should** always produce an output but things will crash if it doesn't. Can we extract the sample ID from the `meta` map instead?

**Comment by gregdenay** [comment]
Hard filtering based on read number is disabled in [1c3d3fb](https://github.com/bio-raum/FooDMe2/commit/1c3d3fb04cf77aee9cd0942565753b4b98d04410).
Samples will now soft fail in subsequent steps (e.g. clustering) or keep going to the end. 

We will probably need to work on the QC checking at the repot level as soon as we have some guidelines therefore.

**Comment by gregdenay** [comment]
First failure point is the learError rate process. There we could check if the fastq.gz are empty and just create a NULL object as rds.

It seems like empty tar.gz comming out of the initial filtering step are 21 bytes `file.size(fnFs)`
A clean solution would be to count `@` or even lines but I can't seem to figure out how to do that on a gzipped file in R without unpacking it.

**Comment by gregdenay** [comment]
`n_lines <- as.integer(system(sprintf('gunzip -c %s | wc -l', fastq), intern= TRUE))`
should work, without actually reading the file in R, should be ok perfomance wise

**Comment by gregdenay** [comment]
Up from [6e743b9](https://github.com/bio-raum/FooDMe2/commit/6e743b96c3ff3e587771fd6b74c7b6058e628301) empty fastq produced by cutadapt will be forwared until the end of the pipeline and samples appear in the report. 

Should still check what happens in case (1) all read are filtered by dada filter steps or (2) no reads can be merged.

**Comment by gregdenay** [comment]
Fixed the chimera process for empty input and that's about all for the test cases I could think of. 
We may have to add some more exceptions in the future but it should catch most problems as of now.
